sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: questionnaire
    username: root
    password: 68942569
  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketName: foufoufiles